const facilities = [
  {
    id: 1,
    name: "King Faisal Hospital",
    hours: "9 PM - 5 AM",
    distance: "A few kilometers away",
    coordinates: { lat: -1.945, lng: 30.059 },
  },
  {
    id: 2,
    name: "Kaniynya Health Center",
    hours: "9 PM - 5 AM",
    distance: "A few kilometers away",
    coordinates: { lat: -1.957, lng: 30.09 },
  },
  {
    id: 3,
    name: "Nyanza Health Center",
    hours: "9 PM - 5 AM",
    distance: "A few kilometers away",
    coordinates: { lat: -1.934, lng: 30.134 },
  },
  {
    id: 4,
    name: "Muhima Health Center",
    hours: "24/7",
    distance: "5 km",
    coordinates: { lat: -1.957, lng: 30.061 },
  },
  {
    id: 5,
    name: "Rwanda Charity Eye Hospital",
    hours: "8 AM - 5 PM",
    distance: "6 km",
    coordinates: { lat: -1.962, lng: 30.115 },
  },
  {
    id: 6,
    name: "Gikondo Health Center",
    hours: "9 AM - 6 PM",
    distance: "7 km",
    coordinates: { lat: -1.946, lng: 30.107 },
  },
  {
    id: 7,
    name: "Kigali University Hospital",
    hours: "9 AM - 7 PM",
    distance: "10 km",
    coordinates: { lat: -1.948, lng: 30.048 },
  },
  {
    id: 8,
    name: "Kimironko Health Center",
    hours: "24/7",
    distance: "4 km",
    coordinates: { lat: -1.967, lng: 30.133 },
  },
  {
    id: 9,
    name: "Remera Health Center",
    hours: "9 AM - 6 PM",
    distance: "8 km",
    coordinates: { lat: -1.961, lng: 30.097 },
  },
  {
    id: 10,
    name: "Nyarutarama Medical Center",
    hours: "8 AM - 5 PM",
    distance: "3 km",
    coordinates: { lat: -1.931, lng: 30.131 },
  },
];
